"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

from main import APP_NAME

APP = ['main.py']

DATA_FILES = []
OPTIONS = {
    "plist": {
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": APP_NAME,
        "CFBundleInfo": '0.1.0',
        "NSHumanReadableCopyright": 'BugenZhao 2019, All Rights Reserved'
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
